### ISSUE TITLE
Error in Python 3+ (easily fixed)

### ISSUE THREAD

**Issue by psavas** [bwesterb/blame-bird#8]
Thanks for a great script!

Just pointing out that on line 64, there is a python 2 style print call:

`print '\n'.join(zonefiles[zone_name2id[sys.argv[1]]])`

This seems to throw an error with python 3. Changing it to the following works however:

`print('\n'.join(zonefiles[zone_name2id[sys.argv[1]]]))`

**Comment by bwesterb** [comment]
Thanks.
